version: '3.4'

services:
  planetsideelo:
    image: planetsideelo
    build:
      context: .
      dockerfile: Dockerfile
    links:
     - db
  db:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_DATABASE: 'planetside_data'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'pugs_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pugs1337'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pugs1337'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro